spring:
  application:
    name: hodor-admin
  profiles:
    include: core
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    defaultPropertyInclusion: NON_NULL

server:
  servlet:
    context-path: /hodor/admin/
  port: 8089

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.dromara.hodor.admin.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

hodor:
  admin:
    apiKey: b50fd4d4d71935b7c2a001b87f068c4f
    role: admin
  client:
    registryAddress: http://localhost:8081/hodor
    appName: hodor-admin
    appKey: hodor-admin
    timeout: 3000
  database:
    type: mysql
    driverClass: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hodor?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus-join:
  # 打印 mybatis plus join banner
  banner: false
  sub-table-logic: true
  ms-cache: true
  logic-del-type: where
