spring:
  application:
    name: hodor-actuator-agent

hodor:
  commons:
    appName: hodor-actuator-agent
    appKey: 1234567
    port: 46367
    registryAddress: http://localhost:8081,localhost:8082,localhost:8083/hodor
    queueSize: 5000
    poolSize: 500
    dataPath: E:\\data\\hodor-actuator\\agent
    jobtypePlugins: E:\\data\\hodor-actuator\\agent\\plugins
    dataSourceConfig:
      type: h2
      dataSourceClassName: org.h2.jdbcx.JdbcDataSource
      url: jdbc:h2:file:E:\\data\\hodor-actuator\\agent\\db\\db_hodor;IGNORECASE=TRUE;AUTO_SERVER=TRUE
      # url: jdbc:h2:tcp://localhost:9090/E:\\data\\hodor-scheduler\\db_hodor;IGNORECASE=TRUE
      username: test
      password: test
      dataSourceProperties:
        minimumIdle: 4
        maximumPoolSize: 16
logging:
  level:
    root: info
    web: info
    sql: info
