spring:
   datasource:
     driver-class-name: ${database.driverClass}
     url: ${database.url}
     username: ${database.username}
     password: ${database.password}

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  typeEnumsPackage: org.dromara.hodor.model.enums
  configuration:
    map-underscore-to-camel-case: true
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler