spring:
   profiles:
     active: local
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/hodor?useUnicode=true&characterEncoding=utf8
     username: root
     password: root

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true